title = "Berknell Financial Group"
baseURL = "/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "Work"
    url = "/work"
  [[menu.header]]
    weight = 3
    name = "Blog"
    url = "/blog"
  [[menu.header]]
    weight = 4
    name = "Service"
    url = "#"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Advice with You In Mind&trade;"
    subtitle = "Berknell Financial Group - a fiduciary financial planning and investment management firm dedicated to providing solutions to your financial concerns. "

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "Simply stated: Berknell is about you. As proud fiduciaries, our independence lends us the autonomy and flexibility to always put you first. We call this Advice With You In Mind&trade;."
    paragraph = "Here we strive to meet our clients, regardless or age, where they are and successfully get them to their goals through sound planning and disciplined evidence-based investment management. Through a deep relationship with you, we plan on being your partner and counselor every step of the way."

  [params.call]
    enable = true
    title = "We design hella experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Advice with You In Mind™"
    content = "We are people. You can expect your advisor to have a personal touch, too . We seek to handle the hard stuff with you so you won't always have to. Instead, spend lives precious moments making memories with the ones that you love."



  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
